### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TetroYT** [provsalt/DropParty#3]
Have the ‘Drop party will start in’ at intervals not at every minute for example 

will start in 2 hours, 1 hour, 30 minutes, 10 minutes, 5 minutes, 3 2 1 etc

because its sending 256 messages in my chat which just isnt needed 

and add a /dp time or something so players can then check when it will start

**Comment by provsalt** [comment]
This is a bug tracker not a suggestion reporter
